### Đăng ký tài khoản ADMIN
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "adminN",
  "password": "129012",
  "email": "adminN@gmail.com",
  "role": "ADMIN"
}

<> 2025-09-06T231255.200.json

### Đăng ký tài khoản CUSTOMER
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "customer1",
  "password": "123456",
  "email": "customer1@example.com",
  "role": "CUSTOMER"
}

<> 2025-09-06T231331.400.json
<> 2025-09-06T231317.400.json
<> 2025-09-06T231117.200.json

### Đăng nhập với tài khoản ADMIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "123456"
}

<> 2025-09-06T231859.200.json
<> 2025-09-06T231206.200.json
<> 2025-09-06T231144.200.json
<> 2025-09-06T231129.200.json

### Đăng nhập với tài khoản CUSTOMER
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "customer1",
  "password": "123456"
}

<> 2025-09-06T231437.200.json

### Tạo sản phẩm
#Cookie: JSESSIONID={{adminJSESSIONID}}
POST http://localhost:8080/api/products
Content-Type: application/json
Cookie:  JSESSIONID=C98BD694AA3CFF7D7BA5267A11223DA1

{
  "name": "Laptop",
  "description": "High-end laptop",
  "price": 1000.0,
  "stock": 10
}

<> 2025-09-09T095926.401.json
<> 2025-09-09T095856.401.json
<> 2025-09-09T084434.401.json
<> 2025-09-09T084309.401.json
<> 2025-09-09T084134.401.json

### Sửa sản phẩm
PUT http://localhost:8080/api/products/1
Content-Type: application/json
Cookie:  JSESSIONID=C98BD694AA3CFF7D7BA5267A11223DA1

{
  "name": "Laptop Pro",
  "description": "Updated laptop",
  "price": 1200.0,
  "stock": 15
}

### Xóa sản phẩm
DELETE http://localhost:8080/api/products/1
Content-Type: application/json
Cookie:  JSESSIONID=C98BD694AA3CFF7D7BA5267A11223DA1

### Xem danh sách sản phẩm (ADMIN hoặc CUSTOMER)
GET http://localhost:8080/api/products
Content-Type: application/json
Cookie: JSESSIONID=CF6250EB34737F6066189E2D769DE84D

### Thêm sản phẩm vào giỏ
POST http://localhost:8080/api/cart/add
Content-Type: application/json
Cookie: JSESSIONID=CF6250EB34737F6066189E2D769DE84D

{
  "productId": 1
}

### Xem giỏ hàng
GET http://localhost:8080/api/cart
Content-Type: application/json
Cookie: JSESSIONID={CF6250EB34737F6066189E2D769DE84D

### Tạo đơn hàng
POST http://localhost:8080/api/orders
Content-Type: application/json
Cookie: JSESSIONID=CF6250EB34737F6066189E2D769DE84D

{
  "productId": 1,
  "quantity": 2
}

### Xem lịch sử đơn hàng
GET http://localhost:8080/api/orders
Content-Type: application/json
Cookie: JSESSIONID=CF6250EB34737F6066189E2D769DE84D